server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZenoJHZhang/springCloudTest
eureka:
  client:
    service-url:
      defaultZone: http://server1:8081/eureka/
